"""Added Document model and updated Record model

Revision ID: 7552df94427a
Revises: 84f6b9ff6076
Create Date: 2023-11-02 13:54:59.615241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7552df94427a'
down_revision = '84f6b9ff6076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_pmid'), 'documents', ['pmid'], unique=False)
    op.add_column('records', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'records', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'document_id')
    op.drop_index(op.f('ix_documents_pmid'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
