comment:
  require_changes: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

components_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: argilla
      name: argilla
      paths:
        - argilla/src/argilla
    - component_id: extralit
      name: extralit
      paths:
        - argilla/src/extralit
    - component_id: argilla-server
      name: argilla-server
      paths:
        - argilla-server
    - component_id: argilla-frontend
      name: argilla-frontend
      paths:
        - argilla-frontend
