repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: extralit/mkdocs.yml|examples/deployments/k8s
      - id: end-of-file-fixer
        exclude_types: [text, jupyter]
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff-format

  ##############################################################################
  # extralit SDK specific hooks
  ##############################################################################
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: "Remove unused imports and variables"
        files: '^extralit/.*\.py$'
        args:
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--in-place"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        files: 'extralit/src/.*\.py$'
        args:
          - --fix
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in Python source files"
        files: '^extralit/.*\.py$'
        exclude: ^extralit/docs/snippets/
        args:
          - --license-filepath
          - extralit/LICENSE_HEADER
          - --fuzzy-match-generates-todo
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: '^extralit/.*\.ipynb$'
        args:
          - --keep-count
          - --keep-output
          # - --keep-prompt-number
          # - --keep-cell-ids
          # - --keep-markdown
          # - --keep-output-timestamp
          # - --keep-execution-count
          # - --keep-metadata
          # - --keep-version

  ##############################################################################
  # extralit-server specific hooks
  ##############################################################################
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: "Remove unused imports and variables in extralit-server"
        files: '^extralit-server/.*\.py$'
        args:
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--in-place"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        files: 'argila-server/src/.*\.py$'
        args:
          - --fix

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in Python source files"
        files: '^extralit-server/.*\.py$'
        args:
          - --license-filepath
          - extralit-server/LICENSE_HEADER
          - --fuzzy-match-generates-todo

  ##############################################################################
  # argilla-v1 SDK specific hooks
  ##############################################################################
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: "Remove unused imports and variables"
        files: '^argilla-v1/.*\.py$'
        args:
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--in-place"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        files: 'argilla-v1/src/.*\.py$'
        args:
          - --fix
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in Python source files"
        files: '^argilla-v1/.*\.py$'
        args:
          - --license-filepath
          - extralit/LICENSE_HEADER
          - --fuzzy-match-generates-todo

  ##############################################################################
  # argilla-frontend specific hooks
  ##############################################################################
  - repo: local
    hooks:
      - id: frontend-lint
        name: "Lint and fix argilla-frontend files"
        entry: bash -c 'cd argilla-frontend && npx eslint --fix "${@#argilla-frontend/}" || true'
        language: system
        files: '^argilla-frontend/.*\.(js|ts|vue)$'
        pass_filenames: true

  ##############################################################################
  # Helm lint hook
  ##############################################################################
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
      - id: helmlint
        name: Helm lint
        files: '^examples/deployments/k8s/.*\.yaml$'
        args: ["helm", "lint", "examples/deployments/k8s/"]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip:
    - helmlint # Disabling helmlint on CI by now because helm dependency is not available
    - frontend-eslint # Requires npm dependencies to be installed in argilla-frontend
    - frontend-prettier # Requires npm dependencies to be installed in argilla-frontend
    - frontend-lint # Requires npm dependencies to be installed in argilla-frontend
  submodules: false
