coverage:
  status:
    project:
      default:
        enabled: false
    patch:
      default:
        enabled: false

flags:
  frontend:
    paths:
      - extralit-frontend/
    carryforward: true
  extralit:
    paths:
      - extralit/src/extralit/
    carryforward: true
  extralit_server:
    paths:
      - extralit-server/
    carryforward: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

  individual_components:
    - component_id: extralit
      name: extralit
      paths:
        - extralit/src/extralit/**

    - component_id: extralit-server
      name: extralit-server
      paths:
        - extralit-server/**

    - component_id: extralit-frontend
      name: extralit-frontend
      paths:
        - extralit-frontend/**
