x-common-variables: &common-variables
  EXTRALIT_HOME_PATH: /var/lib/extralit
  EXTRALIT_ELASTICSEARCH: http://elasticsearch:9200
  EXTRALIT_DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/extralit
  EXTRALIT_REDIS_URL: redis://redis:6379/0

services:
  extralit:
    image: extralitdev/extralit-server:latest
    restart: unless-stopped
    ports:
      - "6900:6900"
    environment:
      <<: *common-variables
      USERNAME: extralit
      PASSWORD: 12345678
      API_KEY: extralit.apikey
      WORKSPACE: default
      # Uncomment the following line to reindex Extralit datasets into the search engine when starting up
      # REINDEX_DATASETS: 1
      # Opt-out for telemetry https://huggingface.co/docs/huggingface_hub/main/en/package_reference/utilities#huggingface_hub.utils.send_telemetry
      # HF_HUB_DISABLE_TELEMETRY: 1
      # Opt-out for telemetry https://huggingface.co/docs/huggingface_hub/main/en/package_reference/utilities#huggingface_hub.utils.send_telemetry
      # HF_HUB_OFFLINE: 1
    networks:
      - extralit
    volumes:
      # EXTRALIT_HOME_PATH is used to define where Extralit will save it's application data.
      # If you change EXTRALIT_HOME_PATH value please copy that same value to extralitdata volume too.
      - extralitdata:/var/lib/extralit
    depends_on:
      - postgres
      - elasticsearch
      - redis

  worker:
    image: extralitdev/extralit-server:latest
    environment:
      <<: *common-variables
      BACKGROUND_NUM_WORKERS: 2
    networks:
      - extralit
    depends_on:
      - postgres
      - elasticsearch
      - redis
    command: sh -c 'python -m extralit_server worker --num-workers $${BACKGROUND_NUM_WORKERS}'

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: extralit
    networks:
      - extralit
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-29T01-40-52Z
    command: minio server /data --console-address :9090
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    # networks:
    #   - extralit
    ports:
      - "9000:9000"
      - "9090:9090"
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 256M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
      - node.name=elasticsearch
      - cluster.name=es-extralit-local
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis
    networks:
      - extralit
    ports:
      - "6379:6379"

networks:
  extralit:
    driver: bridge

volumes:
  extralitdata:
  elasticdata:
  postgresdata:
