version: "3.8"

services:
  argilla:
    image: argilla/argilla-server:latest
    ports:
      - "6900:6900"
    environment:
      - ARGILLA_AUTH_SECRET_KEY=${ARGILLA_AUTH_SECRET_KEY}
      - ARGILLA_DATABASE_URL=${ARGILLA_DATABASE_URL}
      - ARGILLA_ELASTICSEARCH=${ARGILLA_ELASTICSEARCH}
      - ARGILLA_REDIS_URL=${ARGILLA_REDIS_URL}
      - ARGILLA_DEFAULT_USERNAME=argilla
      - ARGILLA_DEFAULT_PASSWORD=12345678
      - ARGILLA_DEFAULT_API_KEY=argilla.apikey
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - argilladata:/data

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  argilladata:
  postgresdata:
  elasticdata: 