# Use a Debian-based image suitable for GitHub Codespaces
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Copy the devcontainer setup file into the container
# COPY .devcontainer/docker-compose/setup.sh /workspaces/setup.sh
# RUN chmod +x /workspaces/setup.sh
