version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../../..:/workspaces:cached      
    command: sleep infinity
    depends_on:
      - elasticsearch
      - postgres
      - minio
    network_mode: host
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
    networks:
      - argilla
    deploy:
      resources:
        limits:
          memory: 512M

  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: argilla
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - argilla
    deploy:
      resources:
        limits:
          memory: 256M

  minio:
    image: quay.io/minio/minio:latest
    command: minio server /data --console-address :9090
    env_file:
      - .env.dev
    environment:
      MINIO_ACCESS_KEY_FILE: /run/secrets/access_key
      MINIO_SECRET_KEY_FILE: /run/secrets/secret_key
    volumes:
      - ./secrets:/run/secrets:ro
    ports:
      - "9000:9000"
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  argilla:
    driver: bridge