apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla-server-deployment
  labels:
    app: argilla-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argilla-server
  template:
    metadata:
      labels:
        app: argilla-server
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: alpine/curl:latest
          command: [ "sh", "-c",
            "ELASTICSEARCH_URL='https://elastic:$(ELASTIC_PASSWORD)@elasticsearch-master:9200'; echo $ELASTICSEARCH_URL; status_code=$(curl -s -k -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          while [ $status_code -ne 200 ]; do sleep 5; status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          echo Sleeping...; done; echo Elasticsearch Connected " ]
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
      containers:
        - name: argilla-server
          image: itnrecal-argilla-hf
          ports:
            - containerPort: 6900
          resources:
            requests:
              cpu: "0.5"
            limits:
              cpu: "1"
          env:
            - name: ARGILLA_ELASTICSEARCH_HOST
              value: "elasticsearch-master:9200"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
            - name: ARGILLA_ELASTICSEARCH_CA_PATH
              value: /usr/share/elasticsearch/config/certs/ca.crt
          volumeMounts:
            - name: elasticsearch-master-certs
              mountPath: /usr/share/elasticsearch/config/certs
      volumes:
        - name: elasticsearch-master-certs
          secret:
            secretName: elasticsearch-master-certs
      imagePullSecrets:
      - name: regcred