blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://docs.extralit.io/
    about: Check our documentation for guides and information.
  - name: 🗯 Community Discussions
    url: https://join.slack.com/t/extralit/shared_invite/zt-3gw1ah8bl-AiVNrkIVYOL4yVGOxN8WFw
    about: Our Slack Community loves to discuss Extralit and scientific literature review topics