# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class BodyCreateTokenTokenPost(BaseModel):
    password: str = Field(..., title="Password")
    username: str = Field(..., title="Username")


class Source(Enum):
    response = "response"
    suggestion = "suggestion"


class ProjectionCell(BaseModel):
    question_name: str = Field(..., title="Question Name")
    source: Optional[Source] = Field(None, title="Source")
    value: Any = Field(None, title="Value")


class ProjectionRecord(BaseModel):
    cells: list[ProjectionCell] = Field(..., title="Cells")
    record_id: UUID = Field(..., title="Record Id")
    reference: str = Field(..., title="Reference")
    schema_id: UUID = Field(..., title="Schema Id")


class ProjectionView(BaseModel):
    records: list[ProjectionRecord] = Field(..., title="Records")
    reference: str = Field(..., title="Reference")
    total_records: int = Field(..., title="Total Records")


class QuestionType(Enum):
    text = "text"
    rating = "rating"
    label_selection = "label_selection"
    multi_label_selection = "multi_label_selection"
    ranking = "ranking"
    span = "span"
    table = "table"


class QuestionUpdate(BaseModel):
    columns: Optional[list[str]] = Field(None, title="Columns")
    description: Optional[str] = Field(None, title="Description")
    required: Optional[bool] = Field(None, title="Required")
    settings: Optional[dict[str, Any]] = Field(None, title="Settings")
    title: Optional[str] = Field(None, title="Title")


class Op(Enum):
    eq = "eq"
    in_ = "in"
    ge = "ge"
    le = "le"


class RecordFilter(BaseModel):
    column: str = Field(..., title="Column")
    op: Op = Field(..., title="Op")
    value: Any = Field(..., title="Value")


class RecordSearchQuery(BaseModel):
    filters: Optional[list[RecordFilter]] = Field(None, title="Filters")
    limit: Optional[conint(ge=1, le=1000)] = Field(50, title="Limit")
    offset: Optional[conint(ge=0)] = Field(0, title="Offset")
    text: Optional[str] = Field(None, title="Text")


class RefreshTokenRequest(BaseModel):
    refresh_token: str = Field(..., title="Refresh Token")


class ResponseStatus(Enum):
    draft = "draft"
    submitted = "submitted"
    discarded = "discarded"


class ResponseUpsert(BaseModel):
    status: ResponseStatus
    values: Optional[dict[str, dict[str, Any]]] = Field(None, title="Values")


class SchemaCreate(BaseModel):
    name: constr(min_length=1, max_length=200) = Field(..., title="Name")
    settings: Optional[dict[str, Any]] = Field(None, title="Settings")
    workspace_id: UUID = Field(..., title="Workspace Id")


class SchemaStatus(Enum):
    draft = "draft"
    published = "published"


class SchemaUpdate(BaseModel):
    name: Optional[constr(min_length=1, max_length=200)] = Field(None, title="Name")
    settings: Optional[dict[str, Any]] = Field(None, title="Settings")


class SchemaVersionCreate(BaseModel):
    body: str = Field(
        ...,
        description="Pandera DataFrameSchema serialized via .to_json()",
        title="Body",
    )
    review_widgets: Optional[dict[str, dict[str, Any]]] = Field(
        None, title="Review Widgets"
    )


class SchemaVersionRead(BaseModel):
    checksum: str = Field(..., title="Checksum")
    columns_cache: list[dict[str, Any]] = Field(..., title="Columns Cache")
    etag: str = Field(..., title="Etag")
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    object_key: str = Field(..., title="Object Key")
    object_version_id: Optional[str] = Field(..., title="Object Version Id")
    parent_version_id: Optional[UUID] = Field(..., title="Parent Version Id")
    review_widgets: dict[str, dict[str, Any]] = Field(..., title="Review Widgets")
    schema_id: UUID = Field(..., title="Schema Id")
    version: int = Field(..., title="Version")


class SuggestionType(Enum):
    model = "model"
    human = "human"
    selection = "selection"


class SuggestionUpsert(BaseModel):
    agent: Optional[str] = Field(None, title="Agent")
    question_id: UUID = Field(..., title="Question Id")
    score: Optional[Union[float, list[float]]] = Field(None, title="Score")
    type: Optional[SuggestionType] = None
    value: Any = Field(..., title="Value")


class Token(BaseModel):
    access_token: str = Field(..., title="Access Token")
    refresh_token: Optional[str] = Field(None, title="Refresh Token")
    token_type: Optional[str] = Field("bearer", title="Token Type")


class V2RecordStatus(Enum):
    pending = "pending"
    completed = "completed"
    discarded = "discarded"


class QuestionCreate(BaseModel):
    columns: list[str] = Field(..., min_length=1, title="Columns")
    description: Optional[str] = Field(None, title="Description")
    name: constr(min_length=1, max_length=200) = Field(..., title="Name")
    required: Optional[bool] = Field(False, title="Required")
    settings: Optional[dict[str, Any]] = Field(None, title="Settings")
    title: constr(min_length=1) = Field(..., title="Title")
    type: QuestionType


class QuestionRead(BaseModel):
    columns: list[str] = Field(..., title="Columns")
    description: Optional[str] = Field(..., title="Description")
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    name: str = Field(..., title="Name")
    required: bool = Field(..., title="Required")
    schema_id: UUID = Field(..., title="Schema Id")
    settings: dict[str, Any] = Field(..., title="Settings")
    title: str = Field(..., title="Title")
    type: QuestionType
    updated_at: AwareDatetime = Field(..., title="Updated At")


class Questions(BaseModel):
    items: list[QuestionRead] = Field(..., title="Items")


class RecordRead(BaseModel):
    external_id: Optional[str] = Field(..., title="External Id")
    fields: dict[str, Any] = Field(..., title="Fields")
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    metadata: Optional[dict[str, Any]] = Field(None, title="Metadata")
    reference: str = Field(..., title="Reference")
    schema_id: UUID = Field(..., title="Schema Id")
    schema_version_id: UUID = Field(..., title="Schema Version Id")
    status: V2RecordStatus
    updated_at: AwareDatetime = Field(..., title="Updated At")


class RecordUpsert(BaseModel):
    external_id: Optional[str] = Field(None, title="External Id")
    fields: dict[str, Any] = Field(..., title="Fields")
    metadata: Optional[dict[str, Any]] = Field(None, title="Metadata")
    reference: constr(min_length=1, max_length=500) = Field(..., title="Reference")
    schema_version_id: Optional[UUID] = Field(
        None,
        description="Pin to a specific version; defaults to the schema's current_version_id",
        title="Schema Version Id",
    )
    status: Optional[V2RecordStatus] = None


class Records(BaseModel):
    items: list[RecordRead] = Field(..., title="Items")
    total: int = Field(..., title="Total")


class RecordsBulkUpsert(BaseModel):
    items: list[RecordUpsert] = Field(..., max_length=500, min_length=1, title="Items")


class ReferenceGroup(BaseModel):
    records: list[RecordRead] = Field(..., title="Records")
    schema_id: UUID = Field(..., title="Schema Id")
    schema_name: str = Field(..., title="Schema Name")


class ReferenceView(BaseModel):
    groups: list[ReferenceGroup] = Field(..., title="Groups")
    reference: str = Field(..., title="Reference")
    total_records: int = Field(..., title="Total Records")


class ResponseRead(BaseModel):
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    record_id: UUID = Field(..., title="Record Id")
    status: ResponseStatus
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: UUID = Field(..., title="User Id")
    values: Optional[dict[str, Any]] = Field(..., title="Values")


class SchemaRead(BaseModel):
    current_version_id: Optional[UUID] = Field(..., title="Current Version Id")
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    name: str = Field(..., title="Name")
    settings: dict[str, Any] = Field(..., title="Settings")
    status: SchemaStatus
    updated_at: AwareDatetime = Field(..., title="Updated At")
    workspace_id: UUID = Field(..., title="Workspace Id")


class Schemas(BaseModel):
    items: list[SchemaRead] = Field(..., title="Items")


class SuggestionRead(BaseModel):
    agent: Optional[str] = Field(..., title="Agent")
    id: UUID = Field(..., title="Id")
    inserted_at: AwareDatetime = Field(..., title="Inserted At")
    question_id: UUID = Field(..., title="Question Id")
    record_id: UUID = Field(..., title="Record Id")
    score: Optional[Union[float, list[float]]] = Field(..., title="Score")
    type: Optional[SuggestionType]
    updated_at: AwareDatetime = Field(..., title="Updated At")
    value: Any = Field(..., title="Value")


class Suggestions(BaseModel):
    items: list[SuggestionRead] = Field(..., title="Items")
