apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8-storage-policy
  labels:
    app: elasticsearch
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 4Gi  # specify the size of the volume
  volumeMode: Filesystem  # can also be Block
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  storageClassName: k8s-storage-policy  # name of the StorageClass
  persistentVolumeReclaimPolicy: Delete  # Retain the volume data when the PVC is deleted
  local:
    path: "/Users/jonnytr/kind-volumes/elasticsearch"  # path on the host where the data is stored
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane  # replace with your node name
