# Project information
site_name: Extralit Docs
site_url: https://docs.extralit.ai/
site_author: Extralit
site_description: Data-centric tool for AI builders
copyright: Copyright &copy; 2023 - 2024 Extralit

# Repository
repo_name: extralit/extralit
repo_url: https://github.com/extralit/extralit/
edit_uri: edit/main/argilla/docs/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/extralit/shared_invite/zt-2kt8t12r7-uFj0bZ5SPAOhRFkxP7ZQaQ

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src/argilla

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/glossary.md
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # activating permalink: true makes the anchor link works in the notebooks
  - toc:
      permalink: true

plugins:
  - search
  - open-in-new-tab
  - gen-files:
      scripts:
        - docs/scripts/gen_changelog.py
        # - docs/scripts/gen_popular_issues.py
        # - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          selection:
            inherited_members: true # Allow looking up inherited methods
          rendering:
            show_root_toc_entry: true
            show_root_heading: true # actually display anything at all...
            # show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false # don't include source code
            members_order: source # order methods according to their order of definition in the source code, not alphabetical order
            heading_level: 4
            # hide private members
            private: true
  - social
  - mknotebooks

# Documentation Structure
nav:
  - Overview: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Quickstart: getting_started/quickstart.md
      - Deploy with Docker: getting_started/how-to-deploy-argilla-with-docker.md
      - Deploy with Hugging Face Spaces: getting_started/how-to-configure-argilla-on-huggingface.md
  - User Guide:
      - user_guide/index.md
      - Core concepts: user_guide/basic_concepts.md
      - Data Pipeline:
        - PDF preprocessing: user_guide/pdf_preprocessing.md
        - Text and table extraction: user_guide/text_table_extraction.md
        - LLM-assisted extraction: user_guide/llm_extraction.md
        - Consensus review: user_guide/consensus_review.md
        - Data validation: user_guide/data_validation.md
        - Extraction status: user_guide/extraction_status.md
      - User Interface:
        - Navigation and layout: user_guide/navigation_layout.md
        - Create and manage workspace: user_guide/create_manage_workspace.md
        - Search and filter records: user_guide/search_filter.md
        - Performing extractions: user_guide/performing_extractions.md
        - Reviewing and validating data: user_guide/review_validate_data.md
      - Advanced Usage:
        - Customizing extraction schemas: user_guide/customizing_schemas.md
        - Optimizing LLM performance: user_guide/optimizing_llm_performance.md
        - Using the API: user_guide/using_the_api.md

  - Administrator Guide:
      - admin_guide/index.md
      - Setup & Deployment:
        - Installation & configuration: admin_guide/installation.md
        - K8s deployment: admin_guide/k8s_deployment.md
        - Database setup: admin_guide/configuration.md
        - File storage configuration: admin_guide/file_storage.md
      - Server Management:
        - Developer installation: admin_guide/installation.md
        - Manage users and credentials: admin_guide/user.md
        - Manage workspaces: admin_guide/workspace.md
        - Create, update and delete datasets: admin_guide/dataset.md
        - Add, update, and delete records: admin_guide/record.md
        - Distribute the annotation task: admin_guide/distribution.md
        - Annotate datasets: admin_guide/annotate.md
        - Query and filter records: admin_guide/query.md
        - Import and export datasets: admin_guide/import_export.md
      - Advanced:
        - Use Markdown to format rich content: admin_guide/use_markdown_to_format_rich_content.md
        - Migrate your legacy datasets to Argilla V2: admin_guide/migrate_from_legacy_datasets.md
  - Tutorials:
      - tutorials/index.md
  - API Reference:
      - Python SDK: reference/argilla/
      - FastAPI Server:
        - Server configuration: reference/argilla-server/configuration.md
      - Telemetry:
        - Server Telemetry: reference/argilla-server/telemetry.md
  - FAQ: getting_started/faq.md
  - Community:
      - community/index.md
      - How to contribute?: community/contributor.md
      - Issue dashboard: community/popular_issues.md
      - Changelog: community/changelog.md

