"""add schema_versions and record reference

Revision ID: 13da2d87e660
Revises: 54d65879a68e
Create Date: 2026-07-27 11:30:48.225356

The v2->v1 fold deleted four revisions that are live on `origin/develop`:
`9f3010c649c8`, `8136bc88ee3a`, `6393b1a01aa0`, `c1510e93882a`. Any database migrated
before this branch has `alembic_version = 'c1510e93882a'`, a revision that no longer
exists, so both `upgrade head` and `downgrade` fail with:

    Can't locate revision identified by 'c1510e93882a'

Extralit is pre-production, so no data-preserving path is provided. Recover by either:

1. Dropping and rebuilding (preferred — also clears the six orphaned v2 tables
   `schemas`, `schema_versions`, `v2_records`, `v2_questions`, `v2_responses`,
   `v2_suggestions` and their enum types, which no migration drops any more):

       # SQLite (the default; EXTRALIT_DATABASE_URL unset -> ~/.extralit/extralit.db)
       rm -f ~/.extralit/extralit.db
       # Postgres
       dropdb extralit && createdb extralit
       uv run alembic -c src/extralit_server/alembic.ini upgrade head

2. Or, to keep an existing database, stamping past the gap and dropping the v2
   leftovers by hand:

       uv run alembic -c src/extralit_server/alembic.ini stamp 54d65879a68e
       uv run alembic -c src/extralit_server/alembic.ini upgrade head
       # then drop the six v2 tables + enum types manually

   On Postgres option 2 additionally requires dropping the pre-existing `schema_versions`
   table BEFORE upgrading — this revision's CREATE TABLE collides with the v2 table of the
   same name.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13da2d87e660"
down_revision = "54d65879a68e"
branch_labels = None
depends_on = None

DATASETS_SCHEMA_VERSION_FKEY = "datasets_current_schema_version_id_fkey"
NAMING_CONVENTION = {"fk": "%(table_name)s_%(column_0_name)s_fkey"}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schema_versions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("object_version_id", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_version_id"], ["schema_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "version", name="schema_version_dataset_id_version_uq"),
    )
    op.create_index(op.f("ix_schema_versions_dataset_id"), "schema_versions", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_schema_versions_version"), "schema_versions", ["version"], unique=False)
    op.add_column("datasets", sa.Column("current_schema_version_id", sa.Uuid(), nullable=True))
    # The FK is added as a separate statement (not inline in create_table) to break the
    # datasets <-> schema_versions cycle. Batch mode is required because SQLite cannot
    # ALTER-add a constraint; note this differs from the deleted 9f3010c649c8, which used a
    # dialect guard and simply carried no DB-level FK on SQLite. Batch mode recreates
    # `datasets` on SQLite, and NAMING_CONVENTION rewrites the pre-existing workspace_id FK
    # name on that path but not on Postgres — the two dialects end up with different
    # constraint names for that FK. Harmless today (nothing looks it up by name), but it is
    # why a round-trip test on both dialects is worth adding.
    with op.batch_alter_table("datasets", naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.create_foreign_key(
            DATASETS_SCHEMA_VERSION_FKEY, "schema_versions", ["current_schema_version_id"], ["id"], ondelete="SET NULL"
        )
    op.add_column("records", sa.Column("reference", sa.String(), nullable=True))
    op.create_index(op.f("ix_records_reference"), "records", ["reference"], unique=False)
    op.create_index("ix_records_dataset_id_reference", "records", ["dataset_id", "reference"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_records_dataset_id_reference", table_name="records")
    op.drop_index(op.f("ix_records_reference"), table_name="records")
    op.drop_column("records", "reference")
    with op.batch_alter_table("datasets", naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(DATASETS_SCHEMA_VERSION_FKEY, type_="foreignkey")
    op.drop_column("datasets", "current_schema_version_id")
    op.drop_index(op.f("ix_schema_versions_version"), table_name="schema_versions")
    op.drop_index(op.f("ix_schema_versions_dataset_id"), table_name="schema_versions")
    op.drop_table("schema_versions")
    # ### end Alembic commands ###
