"""add schema_versions and record reference

Revision ID: 13da2d87e660
Revises: 54d65879a68e
Create Date: 2026-07-27 11:30:48.225356

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13da2d87e660"
down_revision = "54d65879a68e"
branch_labels = None
depends_on = None

DATASETS_SCHEMA_VERSION_FKEY = "datasets_current_schema_version_id_fkey"
NAMING_CONVENTION = {"fk": "%(table_name)s_%(column_0_name)s_fkey"}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schema_versions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("object_version_id", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_version_id"], ["schema_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "version", name="schema_version_dataset_id_version_uq"),
    )
    op.create_index(op.f("ix_schema_versions_dataset_id"), "schema_versions", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_schema_versions_version"), "schema_versions", ["version"], unique=False)
    op.add_column("datasets", sa.Column("current_schema_version_id", sa.Uuid(), nullable=True))
    with op.batch_alter_table("datasets", naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.create_foreign_key(
            DATASETS_SCHEMA_VERSION_FKEY, "schema_versions", ["current_schema_version_id"], ["id"], ondelete="SET NULL"
        )
    op.add_column("records", sa.Column("reference", sa.String(), nullable=True))
    op.create_index(op.f("ix_records_reference"), "records", ["reference"], unique=False)
    op.create_index("ix_records_dataset_id_reference", "records", ["dataset_id", "reference"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_records_dataset_id_reference", table_name="records")
    op.drop_index(op.f("ix_records_reference"), table_name="records")
    op.drop_column("records", "reference")
    with op.batch_alter_table("datasets", naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(DATASETS_SCHEMA_VERSION_FKEY, type_="foreignkey")
    op.drop_column("datasets", "current_schema_version_id")
    op.drop_index(op.f("ix_schema_versions_version"), table_name="schema_versions")
    op.drop_index(op.f("ix_schema_versions_dataset_id"), table_name="schema_versions")
    op.drop_table("schema_versions")
    # ### end Alembic commands ###
