"""create_document_workflows_table

Revision ID: 54d65879a68e
Revises: 7d6b33203390
Create Date: 2025-08-17 23:12:00.379621

"""

import json

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "54d65879a68e"
down_revision = "7d6b33203390"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("workflow_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), default="pending", nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflows_document_id"), "workflows", ["document_id"], unique=False)
    op.create_index(op.f("ix_workflows_reference"), "workflows", ["reference"], unique=False)
    op.create_index(op.f("ix_workflows_group_id"), "workflows", ["group_id"], unique=False)

    connection = op.get_bind()

    # Find all questions with dynamic question types
    questions_table = sa.table("questions", sa.column("id", sa.Uuid), sa.column("settings", sa.JSON))

    # Query for all questions first, then filter in Python for database compatibility
    all_questions = connection.execute(questions_table.select()).fetchall()

    dynamic_questions = []
    for question in all_questions:
        settings = question.settings
        if isinstance(settings, str):
            try:
                settings = json.loads(settings)
            except (json.JSONDecodeError, TypeError):
                continue

        if isinstance(settings, dict):
            question_type = settings.get("type")
            if question_type in ["dynamic_label_selection", "dynamic_multi_label_selection"]:
                dynamic_questions.append(question)

    # Update each dynamic question to use strict=False
    for question in dynamic_questions:
        settings = question.settings
        if isinstance(settings, str):
            settings = json.loads(settings)

        # Add strict=False to settings
        settings["strict"] = False

        # Update the question type to non-dynamic equivalent
        if settings.get("type") == "dynamic_label_selection":
            settings["type"] = "label_selection"
        elif settings.get("type") == "dynamic_multi_label_selection":
            settings["type"] = "multi_label_selection"

        # Update the question in database
        connection.execute(
            questions_table.update().where(questions_table.c.id == question.id).values(settings=settings)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflows_group_id"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_reference"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_document_id"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
